import "./globals.css";
import { Inter, Roboto } from "next/font/google";

const inter = Inter({
   subsets: ["latin"],
   display: "swap",
   variable: "--font-inter",
});

const roboto = Roboto({
   subsets: ["latin"],
   variable: "--font-roboto-mono",
   weight: ["100", "300", "400", "500", "700"],
});

export const metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({ children }) {
   return (
      <html lang="en">
         <body className={`${roboto.variable} ${inter.variable} font-sans`}>
            {children}
         </body>
      </html>
   );
}
