import Providers from "@/components/providers/Providers";
import "./globals.css";
import { Inter, Roboto } from "next/font/google";

const inter = Inter({
   subsets: ["latin"],
   display: "swap",
   variable: "--font-inter",
});

const roboto = Roboto({
   subsets: ["latin"],
   variable: "--font-roboto-mono",
   weight: ["100", "300", "400", "500", "700"],
});

export const metadata = {
   title: "Web3 Vip Pro",
   description: "Generated by CLB Coder",
};

export default function RootLayout({ children }) {
   return (
      <html lang="en" suppressHydrationWarning={true}>
         <body className={`${roboto.variable} ${inter.variable} font-sans`}>
            <Providers>{children}</Providers>
         </body>
      </html>
   );
}
